Exercice 1

In [1]:
import numpy as np

arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


Exercice 2

In [2]:
lst = [3.14, 2.17, 0, 1, 2]
arr2 = np.array(lst, dtype=int)
print(arr2)

[3 2 0 1 2]


Exercice 3

In [3]:
arr3 = np.arange(1, 10).reshape(3, 3)
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercice 4

In [4]:
arr4 = np.random.rand(4, 5).round(2)
print(arr4)

[[0.   0.3  0.78 0.7  0.79]
 [0.83 0.13 0.73 0.74 0.87]
 [0.12 0.73 0.95 0.53 0.02]
 [0.83 0.71 0.92 0.62 0.46]]


Exercice 5

In [5]:
array = np.array([[21,22,23,22,22],
                  [20,21,22,23,24],
                  [21,22,23,22,22]])

second_row = array[1]
print(second_row)

[20 21 22 23 24]


Exercice 6

In [6]:
arr6 = np.arange(10)
reversed_arr = arr6[::-1]
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


Exercice 7

In [7]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercice 8

In [8]:
arr8 = np.arange(10)
sum_val = np.sum(arr8)
avg_val = np.mean(arr8)
print(f"Sum: {sum_val}, Average: {avg_val}")

Sum: 45, Average: 4.5


Exercice 9 

In [9]:
arr9 = np.arange(1, 21).reshape(4, 5)
print(arr9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercice 10

In [10]:
arr10 = np.arange(10)
odd_numbers = arr10[arr10 % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
